<a href="https://colab.research.google.com/github/kilos11/Tensoflow-by-Ricardo-Solinzki/blob/main/Chapter%C2%A01_Introducing_Machine_Learning_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Understanding Machine Learning**

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf

# Create tensor
msg = tf.strings.join(["Hello ", "TensorFlow!"])
# Launch session
sess = tf.compat.v1.Session()
# Print tensor
sess.run(tf.global_variables_initializer())
print(sess.run(msg))

In [ ]:
t1 = tf.constant([1.5, 2.5, 3.5])
t2 = tf.constant([['b', 'b'], ['b', 'b']])
print(t1)
print(t2)

#zeros, ones, and fill
zero_tensor = tf.zeros([3])
print(zero_tensor)

#the following function call creates a 4-x-4 matrix whose elements equal 1.0:
one_tensor = tf.ones([4, 4])
print(one_tensor)

#The following code creates a three-dimensional tensor whose values are set to 81.0:
fill_tensor = tf.fill([1, 2, 3], 81.0)
print(fill_tensor)


tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
tf.Tensor(
[[b'b' b'b']
 [b'b' b'b']], shape=(2, 2), dtype=string)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[[81. 81. 81.]
  [81. 81. 81.]]], shape=(1, 2, 3), dtype=float32)


## **Creating sequences**

In [ ]:
# the following code creates a 1-x-5 tensor whose elements range from 5.0 to 9.0:
lin_tensor = tf.linspace(5., 9., 5)
print(lin_tensor)


#Unlike linspace, range doesn’t accept the number of elements in the tensor.
#Instead, it computes successive elements by adding a value called a delta. In the
#following code, delta is set to 0.5:
range_tensor = tf.range(3., 7., delta=0.5)
print(range_tensor)


tf.Tensor([5. 6. 7. 8. 9.], shape=(5,), dtype=float32)
tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


## **Creating Tensors with Random Values**

In [ ]:
#Creates a tensor with normally distributed values
'''random_normal(shape, mean=0.0, stddev=1.0,
dtype=tf.float32, seed=None, name=None)'''

#Creates a tensor with normally distributed
#values excluding those lying outside two
#standard deviations
'''truncated_normal(shape, mean=0.0, stddev=1.0,
dtype=tf.float32, seed=None, name=None)'''

#Creates a tensor with uniformly distributed
#values between the minimum and maximum
#values
'''random_uniform(shape, minval=0, maxval=None,
dtype=tf.float32, seed=None, name=None)'''


#Shuffles a tensor along its first dimension
'''random_shuffle(tensor, seed=None, name=None)'''

#Set the seed value for all random number
#generation in the graph
'''set_random_seed(seed)'''

#The following code calls random_normal to generate 20 random values:
rnd_ints = tf.random_normal([10], dtype=tf.float64)
print(rnd_ints)





## **Transforming Tensors**

### *Functions for Transforming Tensors*

In [ ]:
#Changes the tensor’s data type to the given type
'''cast(tensor, dtype, name=None)'''

#Returns a tensor with the same elements as the given
#tensor with the given shape
'''reshape(tensor, shape, name=None)'''

#Removes dimensions of size 1
'''squeeze(tensor, axis=None, name=None,
squeeze_dims=None)'''

#Reverses given dimensions of the tensor
'''reverse(tensor, axis, name=None)'''

#Extracts a portion of a tensor
'''slice(tensor, begin, size, name=None)'''

#Combines a list of tensors into a tensor of greater rank
'''stack(tensors, axis=0, name='stack')'''

#Splits a tensor into a list of tensors of lesser rank
'''unstack(tensor, num=None, axis=0,
name='unstack')'''



# the following code uses reshape to convert a four-element
#vector into a 2-x-2 matrix:
vec = tf.constant([1., 2., 3., 4.])
mat = tf.reshape(vec, [2, 2])
print(vec)
print(mat)


# Create a constant tensor
mat = tf.constant([[1., 2., 3.], [4., 5., 6.]])
# The tensor has shape (2, 3) and contains values from 1 to 6
# Reverse the tensor along the first dimension
rev_mat = tf.reverse(mat, [0])
# The reverse operation flips the tensor along the first dimension (rows)
# This will result in a new tensor with the rows reversed
# Print the original tensor
print(mat)
# Print the reversed tensor
print(rev_mat)


rev_mat1 = tf.reverse(mat, [1])
print(rev_mat1)

rev_mat2 = tf.reverse(mat, [0, 1])
print(rev_mat2)


# Create a constant tensor
mat = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
# The tensor has shape (3, 3) and contains values from 1 to 9
# Slice the tensor
slice_mat = tf.slice(mat, [1, 1], [2, 2])
# The slice starts at index [1, 1] and has a size of [2, 2]
# This will extract a sub-tensor from the original tensor
# Print the sliced tensor
print(slice_mat)



#The following code demonstrates how stack can be used. The function combines
#three one-dimensional tensors into a two-dimensional tensor:
t1 = tf.constant([1., 2.])
t2 = tf.constant([3., 4.])
t3 = tf.constant([5., 6.])
t4 = tf.stack([t1, t2, t3])
print(t1,t2,t3,t4)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[4. 5. 6.]
 [1. 2. 3.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[3. 2. 1.]
 [6. 5. 4.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[6. 5. 4.]
 [3. 2. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5. 6.]
 [8. 9.]], shape=(2, 2), dtype=float32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32) tf.Tensor([3. 4.], shape=(2,), dtype=float32) tf.Tensor([5. 6.], shape=(2,), dtype=float32) tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


## **Creating Operations**

In [ ]:
#The first four functions perform element-wise arithmetic. The following code
#demonstrates how they work:
a = tf.constant([3., 3., 3.])
b = tf.constant([2., 2., 2.])
sum = tf.add(a, b)
diff = tf.subtract(a, b)
prod = tf.multiply(a, b)
quot = tf.divide(a, b)
print(sum,diff,prod,quot)

# The following code demonstrates the difference between them:
a = tf.constant([3, 3, 3])
b = tf.constant([2, 2, 2])
div1 = tf.divide(a, b)
div2 = a / b
div3 = tf.divide(a, b)
div4 = a // b
print(div1,div2,div3,div4)



tf.Tensor([5. 5. 5.], shape=(3,), dtype=float32) tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32) tf.Tensor([6. 6. 6.], shape=(3,), dtype=float32) tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float32)
tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64) tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64) tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64) tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([16.], shape=(1,), dtype=float32) tf.Tensor([2.], shape=(1,), dtype=float32)


##*#Rounding and comparison*

In [ ]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.rint(t)
r3 = tf.ceil(t)
r4 = tf.floor(t)

##*#Exponents and logarithms*

In [ ]:
t = tf.constant([4.])
t1 = tf.square(t)
t2 = tf.sqrt(t)
#t3 = tf.rsqrt(t)
print(t1,t2)

tf.Tensor([16.], shape=(1,), dtype=float32) tf.Tensor([2.], shape=(1,), dtype=float32)


## *#Vector and matrix operations*

In [ ]:
#Returns the sum of products for the elements
#in the given axes
'''tensordot(a, b, axes,
name=None)'''

#Returns the element-wise cross product
'''cross(a, b, name=None)'''

#Returns a matrix with the given diagonal
#values, other values set to zero
'''diag(diagonal, name=None)'''

#Returns the sum of the diagonal elements
'''trace(x, name=None)'''

#Switches rows and columns
'''transpose(x, perm=None,
 name='transpose')'''

#Creates an identity matrix with the given
#shape and data type
'''eye(num_rows,
 num_columns=None,
 batch_shape=None,
 dtype=tf.float32,
 name=None)'''

 #Returns the product of the two input matrices
'''matmul(a, b,
 transpose_a=False,
 transpose_b=False,
 adjoint_a=False,
 adjoint_b=False,
 a_is_sparse=False,
 b_is_sparse=False,
 name=None)'''

 #Returns the norm of the given axis of the
#input tensor with the specified order
'''norm(tensor,
 ord='euclidean',
 axis=None,
 keep_dims=False,
 name=None)'''

 #Returns the tensor x, such that Ax = b, where
#A is a matrix, and b is a vector
'''matrix_solve(A, b,
 adjoint=None,
 name=None)'''

 #Returns the eigenvectors and eigenvalues of
#the given matrix or matrices
'''qr(input, full_matrices=None,
 name=None)'''

 #Factors the matrix into a unitary matrix, a
#diagonal matrix, and the conjugate transpose
#of the unitary matrix
'''svd(tensor,
 full_matrices=False,
 compute_uv=True,
 name=None)'''

 #Executes a custom mathematical operation
'''einsum(equation, *inputs)'''


#I frequently call tensordot to compute the dot product of two one-dimensional
#tensors. The following code shows what this looks like:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
dot = tf.tensordot(t1, t2, 1)# 4*3 + 3*2 + 2*1 = 20
print(dot)

#matmul performs traditional matrix multiplication. That is, it multiplies rows of
#the first tensor by columns of the second tensor and returns a matrix containing
#the sums. The following code shows how this can be used:
# Create two constant tensors
t1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# The tensor t1 has shape (2, 3) and contains values from 1.0 to 6.0
t2 = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
# The tensor t2 has shape (3, 2) and contains values from 1.0 to 6.0
# Perform matrix multiplication
dot2 = tf.matmul(t1, t2)
# The matmul function computes the dot product of two tensors,
# resulting in a new tensor with shape (2, 2)
# Print the result of matrix multiplication
print(dot2)

#The following code calls einsum to transpose a matrix and multiply two matrices
#together:
import tensorflow as tf
# Create two constant matrices
m1 = tf.constant([[1, 2], [3, 4]])
# The matrix m1 has shape (2, 2) and contains values from 1 to 4
m2 = tf.constant([[5, 6], [7, 8]])
# The matrix m2 has shape (2, 2) and contains values from 5 to 8
# Perform einsum operation to transpose m1
e1 = tf.einsum('ij->ji', m1)
# The einsum function performs a transpose operation on matrix m1,
# resulting in a new matrix e1 with shape (2, 2) and transposed values
# Perform einsum operation to matrix multiply m1 and m2
e2 = tf.einsum('ij,jk->ik', m1, m2)
# The einsum function performs matrix multiplication between m1 and m2,
# resulting in a new matrix e2 with shape (2, 2) and the multiplied values
# Print the transposed matrix
print(e1)
# Print the result of matrix multiplication
print(e2)



tf.Tensor(20.0, shape=(), dtype=float32)
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


## *Simple Mathematics Operations*

In [ ]:
# Math with constant tensors
const_a = tf.constant(3.6)
const_b = tf.constant(1.2)
total = const_a + const_b
quot = tf.div(const_a, const_b)

# Math with random tensors
rand_a = tf.random_normal([3], 2.0)
rand_b = tf.random_uniform([3], 1.0, 4.0)
diff = tf.subtract(rand_a, rand_b)

# Vector multiplication
vec_a = tf.linspace(0.0, 3.0, 4)
vec_b = tf.fill([4, 1], 2.0)
prod = tf.multiply(vec_a, vec_b)
dot = tf.tensordot(vec_a, vec_b, 1)

# Matrix multiplication
mat_a = tf.constant([[2, 3], [1, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 1], [3, 7, 2]])
mat_prod = tf.matmul(mat_a, mat_b)

# Execute the operations
with tf.Session() as sess:
 print("Sum: %f" % sess.run(total))
 print("Quotient: %f" % sess.run(quot))
 print("Difference: ", sess.run(diff))
 print("Element-wise product: ", sess.run(prod))
 print("Dot product: ", sess.run(dot))
 print("Matrix product: ", sess.run(mat_prod))